### ISSUE TITLE
How to transform ffi.Array<Int32> to ffi.Point<Int32>?????

### ISSUE THREAD

**Issue by fayfive** [dart-lang/ffi#117]
@ffi.Array.multi([8])
  external ffi.Array<ffi.Pointer<ffi.Uint8>> data;  to

ffi.Pointer<ffi.Pointer<ffi.Uint8>> data

**Comment by dcharkes** [comment]
@fayfive that is not aways possible.

Structs might be backed by `Pointer` (pointing to C memory, when using `calloc` in Dart or C) or `TypedData` (pointing to Dart memory, when returning it by value from an FFI call). You can't get a `Pointer` when it's in Dart memory, because the garbage collector might move the data to another address.

Can you tell us more about your use case?

**Comment by fayfive** [comment]
It's ffmpeg. I use ffigen to generate *.dart.

in frame.h
typedef struct AVFrame {
#define AV_NUM_DATA_POINTERS 8
    uint8_t *data[AV_NUM_DATA_POINTERS]; 

to
in dart
class AVFrame extends ffi.Struct {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Pointer<ffi.Uint8>> data;


in swscale.h
int sws_scale(struct SwsContext *c, const uint8_t *const srcSlice[],

to
in dart
int sws_scale(
    ffi.Pointer<SwsContext> c,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> srcSlice,

in c, I can sws_scale(c, AVFrame->data
but in dart how to do it?

**Comment by dcharkes** [comment]
Ah I see. I assume you're not compiling any C/C++ code yourself and usig `ffmpeg` as is.

Do you have a `Pointer<AVFrame>` in Dart? Then we can do a trick because it is the first field in the struct [1].

```dart
final Pointer<AVFrame> avFrame = // FFI call to av_frame_alloc() or something similar [2]
final Pointer<Pointer<Uint8>> data = avFrame.cast();
```

This works because

1. the first field of the struct will have the same memory address as the struct, and
2. we know the struct is in C memory because we have a pointer to it.

[1] https://www.ffmpeg.org/doxygen/4.0/structAVFrame.html
[2] https://www.ffmpeg.org/doxygen/4.0/frame_8h.html

**Comment by fayfive** [comment]
I want to use the date of the AVFrame not AVFrame, that means AVFrame.data
similar like that sws_scale(c, AVFrame.ref.data.
Does your method work?

**Comment by dcharkes** [comment]
> the AVFrame not AVFrame

What do you mean?

It would work for any struct `S` with a `Pointer<S extends Struct>` as long as we want the first field from that struct.

If we want a different field from that struct we need to address https://github.com/dart-lang/sdk/issues/41237.

**Comment by dcharkes** [comment]
Ah I see what you're asking.

Yes `avFrame.ref.data` gives you an `Array` with a `Pointer` inside with an address. `avFrame.cast()` gives you a `Pointer` with an address, which is what you were asking for. The only reason that this works is because in C a struct in memory just starts with the first field. So casting a Pointer to a struct to a Pointer to the first field of that struct works.

**Comment by fayfive** [comment]
Here is my code

`
int sws_scale(
    ffi.Pointer<SwsContext> c,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> srcSlice,
    ffi.Pointer<ffi.Int32> srcStride,
    int srcSliceY,
    int srcSliceH,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> dst,
    ffi.Pointer<ffi.Int32> dstStride,
  ) 
`
`
/////////////////////////////////////////////////////////////
`
`
var _frame = avcodec.av_frame_alloc();
`
`
swscale.sws_scale(_swsCtx, _frame.ref.data, _frame.ref.lineSize, 0,
                videoHeight, picData, picLineSize);
`
I don't know how to transform _frame.ref.data(ffi.Array<ffi.Pointer<ffi.Uint8>>) to  ffi.Pointer<ffi.Pointer<ffi.Uint8>> and
_frame.ref.lineSize(ffi.Array<ffi.Int32>) to ffi.Pointer<ffi.Int32>.

Maybe the question is Clearer.

**Comment by dcharkes** [comment]
For lineSize we need some more tricks to compute the memory address:

```dart
const AV_NUM_DATA_POINTERS = 8;

Pointer<AVFrame> _frame;

// _frame.ref.data but with Pointer<Pointer<Uint8>>, in memory at same address as _frame.
final _frameData = _frame.cast<Pointer<Uint8>>();

// _frame.ref.lineSize but with Pointer<Pointer<Uint32>>, in memory AV_NUM_DATA_POINTERS elements after _frameData.
final _frameLineSize = _frameData.elementAt(AV_NUM_DATA_POINTERS).cast<Pointer<Uint32>>();

swscale.sws_scale(_swsCtx, _frameData, _frameLineSize, 0, videoHeight, picData, picLineSize);
```

You wouldn't need these manual workarounds if we address https://github.com/dart-lang/sdk/issues/41237 and https://github.com/dart-lang/ffigen/issues/246.

* https://github.com/dart-lang/sdk/issues/41237  would do `.elementAt(AV_NUM_DATA_POINTERS)` under the hood.
* https://github.com/dart-lang/ffigen/issues/246 would do generate `.cast<Pointer<Uint32>>()` for you.

**Comment by fayfive** [comment]
@dcharkes 
Thanks a lot!
That means  we can get the parameters of the struct through the pointer of the memory address + offset.
