### ISSUE TITLE
Can I "flutter create -t package" , when I use the so files?

### ISSUE THREAD

**Issue by fayfive** [dart-lang/ffi#121]
I know  I can use the share library by "flutter create -t plugin". But I think  this approach is a little cumbersome. Because I want  to contain the so files in my project. 
For example, I place the so files to the path "flutter_app/linux/lib".
Thanks!

**Comment by dcharkes** [comment]
Context: https://github.com/dart-lang/ffi/issues/118

**Comment by dcharkes** [comment]
Because of the way Flutter plugins are set up (they generate a ton of boilerplate files from a templating system for every target platform), it is not recommended to try to create this boilerplate in an existing package.

Instead, create a Flutter FFI plugin.

Here is a PR adding FFI plugins to Flutter. (Instructions to on how to run it in the PR for if you want to use this before its merged.) 

* https://github.com/flutter/flutter/pull/96225
