### ISSUE TITLE
How to include dynamic library in dart package

### ISSUE THREAD

**Issue by slice-mohit** [dart-lang/ffi#168]
Hey everyone!
I'm trying to create a package which exposes dart bindings for a C++ library. Is it possible to include the dynamic library in the package itself so that anyone can add the package to their project and they don't need to have the dynamic file on their system separately for providing path, just like we can add `.so` file in android and `.a` in ios flutter in case of flutter. Please let me know if this is possible.

**Comment by dcharkes** [comment]
@slice-mohit I'm currently working to get something like this supported for Dart standalone packages so that it would also work in Flutter.

As of right now, you can
1. ship sources a flutter plugins with `flutter create --template=plugin_ffi --platform=...`, or
2. ship a script that downloads the native library during flutter build [see realm_flutter](https://github.com/realm/realm-dart/blob/81c8b913b5c9d639fd5d4f09b069eb4fc87de706/flutter/realm_flutter/android/build.gradle#L85), or
3. ship sources in a Dart standalone package and let users run a build by calling `dart run <your-package>/setup.dart` [see webcrypto](https://github.com/google/webcrypto.dart/blob/master/bin/setup.dart), or
4. make your `bin/setup.dart` download the native library.

**Comment by slice-mohit** [comment]
Thanks @dcharkes. I'll try this out.
