### ISSUE TITLE
Keep supporting Flutter 2

### ISSUE THREAD

**Issue by martin-braun** [dart-lang/ffi#170]
Flutter 2 is not even one year old, but ffi 2.0.1 depends on SDK 2.17.0, which is Flutter 3. Can this be polyfilled to support SDK 2.16.2 (Flutter 2.10.5) for some more time please?

**Comment by dcharkes** [comment]
We bumped to Dart 2.16 because we introduced uses of https://api.dart.dev/stable/2.18.6/dart-ffi/AbiSpecificInteger-class.html.

* https://github.com/dart-lang/ffi/pull/128

We subsequently decided to revert that.

* https://github.com/dart-lang/ffi/pull/141

Which reverted the Dart version back to 2.12.


Then we bumped to 2.17 in

* https://github.com/dart-lang/ffi/pull/144

Most likely due to the reference to https://api.dart.dev/stable/2.18.6/dart-ffi/NativeFinalizer-class.html in the docs, which was introduced in 2.17.

If it's only the docs reference we could possibly try to revert back to Dart 2.12 which is Flutter 2.0.0.

**Comment by dcharkes** [comment]
In general, we'd like to be able to use new features introduces in Dart in this package.

See for example:

* https://github.com/dart-lang/ffi/issues/160

When we address this issue, we would bump to Dart 2.19.

@martin-braun what's your use case for staying at Flutter 2?

**Comment by dcharkes** [comment]
@martin-braun could you try https://github.com/dart-lang/ffi/pull/171 with a dependency override as git dependency to see if it does what you need?

**Comment by martin-braun** [comment]
@dcharkes Thank you for taking action so quick. Unfortunately, I had to decide to bump my plugin to Flutter 3 due to other non-related issues. I wish there was another way. I was requesting the backport, so that another plugin could start to work again, as my plugin is not depending on ffi, directly. 

So in conclusion, it's not an issue anymore. For the future I hope that the Flutter team and Flutter plugin maintainers could try to give longer support times on legacy versions. Maybe an `lts` channel could be considered that plugin maintainers need to follow up.
