### ISSUE TITLE
wasm support

### ISSUE THREAD

**Issue by hanabi1224** [dart-lang/ffi#87]
Currently any dart package that depends on ffi lib does not support web due to its dart:io dependency .
Since many modern native toolchains provide wasm cross-compile support for the web/js, is it possible to provide web platform support in this ffi library that interoperates with wasm? Thanks!

**Comment by dcharkes** [comment]
> Currently any dart package that depends on ffi lib does not support web due to its `dart:io` dependency.

Due to its `dart:ffi` dependency (besides its `dart:io` dependency). `dart:ffi` is not available on the web. Because of this, `package:ffi` is not available on the web.

If you'd like packages wrapping native libraries to be available on the web, those packages would need to be compiled to wasm and one would use `dart:js` to interface with web assembly. One would not use `dart:ffi` nor `package:ffi`.

This needs to be solved on a per package basis, we can't solve it for all packages by doing something in `dart:ffi` or `package:ffi`. Closing issue.
