### ISSUE TITLE
[Question] Throw from native

### ISSUE THREAD

**Issue by alexlapa** [dart-lang/ffi#92]
What is current idiomatic way to throw exceptions from native code to Dart using DL API?

It seems that the only way to do this is `Dart_NewApiError` + `Dart_NewUnhandledExceptionError` + `Dart_PropagateError`.

But, according to docs:
1. > Api error handles are produced when an api function is misused. Dart embedding api function is called with invalid arguments or in an invalid context.

So my understanding is that `ApiError` is not meant to be used as some application-level generic error.

2. > Unhandled exception error handles are produced when, during the execution of Dart code, an exception is thrown but not caught.

So `UnhandledExceptionError` is not meant to be constructed in native code, when there is no Dart code invocation happening.

3. `Dart_PropagateError` is a very error-prone since: `they transfer control non-locally using a setjmp-like mechanism.`.  Id like to avoid using this function in favor of `Dart_SetReturnValue`, but it is not available via DL API.

Of course there are other ways to return error from native functions (returning status codes, passing pointers in arguments), but being able to `throw` from native is the most convenient one.

So i'm wondering if i'm missing something, or it is really the only available way right now? Is there any chance that `Dart_SetReturnValue` will become available via DL API?

**Comment by dcharkes** [comment]
> Dart_PropagateError is a very error-prone since: they transfer control non-locally using a setjmp-like mechanism.. Id like to avoid using this function.

Yes you should.

> Of course there are other ways to return error from native functions (returning status codes, passing pointers in arguments)

Indeed, this is the preferred way of doing it.

> Dart_SetReturnValue

The FFI trampolines and `Dart_PropagateError` are aware of each other, this is not the case with `Dart_SetReturnValue`, the FFI trampolines will just ignore this. (`Dart_NativeArguments` are part of the native runtime entries which are a slow and reflective old mechanism which the FFI is replacing.)

> It seems that the only way to do this is Dart_NewApiError + Dart_NewUnhandledExceptionError + Dart_PropagateError.

If you throw an error in Dart from an FFI callback, you can propagate it, see https://github.com/dart-lang/sdk/search?q=ReturnHandleInCallback.

You could also make the C++ (?) function you're calling from Dart have a try catch, return a status code from there, and still use c++ exceptions internally in your code base, instead of over language boundaries. However, C++ exceptions have their own drawbacks just like `Dart_PropagateError`.

Do you have a use case where throwing is really preferred?

**Comment by alexlapa** [comment]
@dcharkes ,

> Dart_SetReturnValue, the FFI trampolines will just ignore this

Ah, didn't know that.

> Do you have a use case where throwing is really preferred?

Regardless of a use case it is simply a much more convenient way from both sides. Cant think of a scenario where it would be mandatory, just a minor quality of life improvement.

> Indeed, this is the preferred way of doing it.

I've got your point, will stick to that. 

Thanks for your response.
This issue can be closed.
