### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by richard457** [dart-lang/ffi#95]
I want to call C API from the web unfortunately web is not supported. Are there plans to support it?

**Comment by dcharkes** [comment]
Due to its `dart:ffi` dependency (besides its `dart:io` dependency). `dart:ffi` is not available on the web. Because of this, `package:ffi` is not available on the web.

If you'd like packages wrapping native libraries to be available on the web, those packages would need to be compiled to wasm and one would use `dart:js` to interface with web assembly. One would not use `dart:ffi` nor `package:ffi`.

This needs to be solved on a per package basis, we can't solve it for all packages by doing something in `dart:ffi` or `package:ffi`. Closing issue.

_Originally posted by @dcharkes in https://github.com/dart-lang/ffi/issues/87#issuecomment-791372204_
