### ISSUE TITLE
toDartString() check for nullptr

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffi#97]
We could check whether the address != nullptr in `toDartString` as a sanity check.

https://github.com/dart-lang/sdk/issues/45734

**Comment by klavs** [comment]
I am no native developer, but it seems to me that `toDartString` should return `String?` since `Pointer<T>` is inherently nullable.


It would _< insert all the arguments for the benefits of NNBD here >_.

_Given that a native `gpiod.line.name` returns a `const char *`._

#### `String toDartString({int? length})`
Statically valid code, throws exception:
```
String name = gpiod.line.name(line).toDartString();
```
Statically valid code, does not throw exception:
```
Pointer<Utf8> namePtr = gpiod.line.name(line);
String name = namePtr != nullptr ? namePtr.toDartString() : 'unnamed';
```

#### `String? toDartString({int? length})`.
Statically invalid code, would throw exception:
```
String name = gpiod.line.name(line).toDartString();
```
Statically valid code, does not throw exception:
```
String name = gpiod.line.name(line).toDartString() ?? 'unnamed';
```
